questions = [
    # General Knowledge & Daily Life
    {"question": "How many days are in a leap year?", "options": ["364", "365", "366", "367"], "answer": 2},
    {"question": "Which hand is usually used for a handshake?", "options": ["Left", "Right", "Both", "None"], "answer": 1},
    {"question": "What color do you get by mixing red and yellow?", "options": ["Green", "Purple", "Orange", "Pink"], "answer": 2},
    {"question": "How many minutes are in one hour?", "options": ["50", "60", "100", "120"], "answer": 1},
    {"question": "Which of these is a primary color?", "options": ["Green", "Orange", "Red", "Purple"], "answer": 2},
    {"question": "How many continents are there on Earth?", "options": ["5", "6", "7", "8"], "answer": 2},
    {"question": "What is the standard boiling point of water?", "options": ["90°C", "100°C", "110°C", "120°C"], "answer": 1},
    {"question": "Which direction does the sun rise from?", "options": ["North", "South", "East", "West"], "answer": 2},
    {"question": "How many legs does a spider have?", "options": ["4", "6", "8", "10"], "answer": 2},
    {"question": "Which is the largest planet in our solar system?", "options": ["Earth", "Mars", "Jupiter", "Saturn"], "answer": 2},

    # Science & Nature
    {"question": "What gas do humans need to breathe to stay alive?", "options": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"], "answer": 1},
    {"question": "Which organ pumps blood through your body?", "options": ["Lungs", "Brain", "Stomach", "Heart"], "answer": 3},
    {"question": "What is the hardest natural substance on Earth?", "options": ["Gold", "Iron", "Diamond", "Graphite"], "answer": 2},
    {"question": "How many bones are in the adult human body?", "options": ["180", "206", "250", "300"], "answer": 1},
    {"question": "What is the center of an atom called?", "options": ["Electron", "Proton", "Nucleus", "Orbit"], "answer": 2},
    {"question": "Which planet is known as the Red Planet?", "options": ["Venus", "Mars", "Saturn", "Mercury"], "answer": 1},
    {"question": "What do bees collect from flowers to make honey?", "options": ["Pollen", "Petals", "Nectar", "Water"], "answer": 2},
    {"question": "Which is the fastest land animal?", "options": ["Lion", "Cheetah", "Horse", "Greyhound"], "answer": 1},
    {"question": "What force pulls objects toward the Earth?", "options": ["Friction", "Magnetism", "Gravity", "Inertia"], "answer": 2},
    {"question": "Which part of the plant conducts photosynthesis?", "options": ["Roots", "Stem", "Leaf", "Flower"], "answer": 2},

    # Food & Household
    {"question": "What is the main ingredient in bread?", "options": ["Rice", "Flour", "Sugar", "Salt"], "answer": 1},
    {"question": "Which fruit is known for having its seeds on the outside?", "options": ["Apple", "Banana", "Strawberry", "Grape"], "answer": 2},
    {"question": "Where should you store milk to keep it fresh?", "options": ["Pantry", "Countertop", "Refrigerator", "Freezer"], "answer": 2},
    {"question": "What is the common name for Sodium Chloride?", "options": ["Sugar", "Salt", "Pepper", "Baking Soda"], "answer": 1},
    {"question": "Which vitamin is commonly associated with citrus fruits?", "options": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "answer": 2},
    {"question": "What tool is used to measure temperature?", "options": ["Barometer", "Thermometer", "Hygrometer", "Speedometer"], "answer": 1},
    {"question": "Which of these is a dairy product?", "options": ["Eggs", "Cheese", "Tofu", "Honey"], "answer": 1},
    {"question": "How many eggs are in a dozen?", "options": ["6", "10", "12", "24"], "answer": 2},
    {"question": "What do you use to dry your hair quickly?", "options": ["Toaster", "Hairdryer", "Microwave", "Vacuum"], "answer": 1},
    {"question": "What is the main ingredient of guacamole?", "options": ["Tomato", "Onion", "Avocado", "Pepper"], "answer": 2},

    # Geography & Places
    {"question": "In which country is the Eiffel Tower located?", "options": ["Italy", "Germany", "France", "Spain"], "answer": 2},
    {"question": "Which is the smallest continent?", "options": ["Europe", "Antarctica", "Australia", "South America"], "answer": 2},
    {"question": "What is the capital city of Japan?", "options": ["Seoul", "Beijing", "Tokyo", "Bangkok"], "answer": 2},
    {"question": "Which ocean is the largest?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": 3},
    {"question": "In which continent is the Sahara Desert located?", "options": ["Asia", "Africa", "Australia", "North America"], "answer": 1},
    {"question": "Which country has the largest population?", "options": ["USA", "India", "Russia", "Brazil"], "answer": 1},
    {"question": "What is the longest river in the world?", "options": ["Amazon", "Nile", "Mississippi", "Yangtze"], "answer": 1},
    {"question": "Mount Everest is located in which mountain range?", "options": ["Andes", "Rockies", "Alps", "Himalayas"], "answer": 3},
    {"question": "Which country is also a continent?", "options": ["Canada", "Australia", "Brazil", "China"], "answer": 1},
    {"question": "What is the capital of the United States?", "options": ["New York", "Los Angeles", "Washington D.C.", "Chicago"], "answer": 2},

    # Animals & Insects
    {"question": "What is a baby cat called?", "options": ["Puppy", "Kitten", "Cub", "Calf"], "answer": 1},
    {"question": "Which animal is known as the King of the Jungle?", "options": ["Tiger", "Elephant", "Lion", "Bear"], "answer": 2},
    {"question": "Which bird cannot fly?", "options": ["Eagle", "Parrot", "Ostrich", "Sparrow"], "answer": 2},
    {"question": "How many hearts does an octopus have?", "options": ["1", "2", "3", "4"], "answer": 2},
    {"question": "What is the largest mammal in the world?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], "answer": 1},
    {"question": "Which animal is known for its humps?", "options": ["Horse", "Camel", "Donkey", "Cow"], "answer": 1},
    {"question": "What do caterpillars turn into?", "options": ["Bees", "Butterflies", "Ants", "Dragonflies"], "answer": 1},
    {"question": "Which animal has a long trunk?", "options": ["Rhino", "Giraffe", "Elephant", "Zebra"], "answer": 2},
    {"question": "What type of animal is a frog?", "options": ["Mammal", "Reptile", "Amphibian", "Bird"], "answer": 2},
    {"question": "What is a group of lions called?", "options": ["Pack", "Herd", "Pride", "Flock"], "answer": 2},

    # Sports & Entertainment
    {"question": "How many players are on a standard soccer team on the field?", "options": ["9", "10", "11", "12"], "answer": 2},
    {"question": "In which sport would you use a racket?", "options": ["Football", "Tennis", "Basketball", "Golf"], "answer": 1},
    {"question": "How many rings are on the Olympic flag?", "options": ["3", "4", "5", "6"], "answer": 2},
    {"question": "What is the highest score possible in a single frame of bowling?", "options": ["10", "20", "30", "40"], "answer": 2},
    {"question": "Which sport is known as the 'National Pastime' of the USA?", "options": ["Basketball", "Baseball", "Hockey", "Soccer"], "answer": 1},
    {"question": "How many strings does a standard guitar have?", "options": ["4", "5", "6", "7"], "answer": 2},
    {"question": "Which instrument has 88 keys?", "options": ["Violin", "Guitar", "Piano", "Flute"], "answer": 2},
    {"question": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Picasso", "Da Vinci", "Monet"], "answer": 2},
    {"question": "What do you call the person who leads an orchestra?", "options": ["Director", "Conductor", "Producer", "Manager"], "answer": 1},
    {"question": "In chess, which piece can only move diagonally?", "options": ["Rook", "Knight", "Bishop", "King"], "answer": 2},

    # Technology & Modern Life
    {"question": "What does 'WWW' stand for?", "options": ["World Wide Web", "Web Wide World", "Wild World Web", "World Web Wide"], "answer": 0},
    {"question": "Which company makes the iPhone?", "options": ["Samsung", "Microsoft", "Google", "Apple"], "answer": 3},
    {"question": "What is the shortcut for 'Copy' on most computers?", "options": ["Ctrl+X", "Ctrl+V", "Ctrl+C", "Ctrl+S"], "answer": 2},
    {"question": "What is the primary function of a router?", "options": ["Print documents", "Scan photos", "Distribute internet", "Store files"], "answer": 2},
    {"question": "Which of these is a social media platform?", "options": ["Excel", "Instagram", "Photoshop", "Spotify"], "answer": 1},
    {"question": "What does a battery store?", "options": ["Heat", "Water", "Electricity", "Light"], "answer": 2},
    {"question": "Which device is used to type on a computer?", "options": ["Mouse", "Monitor", "Keyboard", "Printer"], "answer": 2},
    {"question": "What is the 'brain' of a computer?", "options": ["RAM", "Hard Drive", "CPU", "Monitor"], "answer": 2},
    {"question": "What do you use to browse the internet?", "options": ["Browser", "Server", "Desktop", "Hardware"], "answer": 0},
    {"question": "What is the most popular search engine?", "options": ["Bing", "Yahoo", "Google", "DuckDuckGo"], "answer": 2},

    # Health & Body
    {"question": "Which organ is responsible for thinking?", "options": ["Heart", "Liver", "Lungs", "Brain"], "answer": 3},
    {"question": "What is the normal body temperature in Celsius?", "options": ["35°C", "37°C", "39°C", "41°C"], "answer": 1},
    {"question": "How many teeth does a normal adult have?", "options": ["24", "28", "32", "36"], "answer": 2},
    {"question": "What do you call a person who treats your teeth?", "options": ["Surgeon", "Pediatrician", "Dentist", "Optometrist"], "answer": 2},
    {"question": "Which sense do you use to hear?", "options": ["Sight", "Smell", "Hearing", "Touch"], "answer": 2},
    {"question": "What is the largest organ of the human body?", "options": ["Heart", "Liver", "Skin", "Lungs"], "answer": 2},
    {"question": "Which part of the eye determines the color?", "options": ["Pupil", "Retina", "Iris", "Cornea"], "answer": 2},
    {"question": "What do we use to see things?", "options": ["Ears", "Eyes", "Nose", "Tongue"], "answer": 1},
    {"question": "How many fingers does a human typically have on one hand?", "options": ["4", "5", "6", "10"], "answer": 1},
    {"question": "Drinking what helps keep you hydrated?", "options": ["Soda", "Coffee", "Water", "Juice"], "answer": 2},

    # Time & Measurements
    {"question": "How many seconds are in a minute?", "options": ["30", "60", "90", "120"], "answer": 1},
    {"question": "How many months have 31 days?", "options": ["4", "6", "7", "8"], "answer": 2},
    {"question": "What is the first day of the week?", "options": ["Monday", "Friday", "Saturday", "Sunday"], "answer": 3},
    {"question": "How many years are in a decade?", "options": ["5", "10", "50", "100"], "answer": 1},
    {"question": "How many centimeters are in a meter?", "options": ["10", "50", "100", "1000"], "answer": 2},
    {"question": "What do we call a period of 100 years?", "options": ["Decade", "Era", "Century", "Millennium"], "answer": 2},
    {"question": "How many hours are in a day?", "options": ["12", "24", "48", "60"], "answer": 1},
    {"question": "What time is 12:00 PM?", "options": ["Midnight", "Noon", "Morning", "Evening"], "answer": 1},
    {"question": "How many seasons are there in a year?", "options": ["2", "3", "4", "6"], "answer": 2},
    {"question": "Which is heavier: 1kg of lead or 1kg of feathers?", "options": ["Lead", "Feathers", "Neither", "Both"], "answer": 2},

    # Miscellaneous
    {"question": "What is the opposite of 'Rich'?", "options": ["Poor", "Happy", "Sad", "Strong"], "answer": 0},
    {"question": "Which of these is a vehicle?", "options": ["House", "Car", "Tree", "Mountain"], "answer": 1},
    {"question": "What do you use to write on a blackboard?", "options": ["Pen", "Pencil", "Chalk", "Marker"], "answer": 2},
    {"question": "Which gas do plants absorb?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], "answer": 2},
    {"question": "How many sides does a triangle have?", "options": ["2", "3", "4", "5"], "answer": 1},
    {"question": "What do you call a shape with four equal sides?", "options": ["Circle", "Triangle", "Square", "Pentagon"], "answer": 2},
    {"question": "Which is the tallest animal?", "options": ["Elephant", "Giraffe", "Ostrich", "Camel"], "answer": 1},
    {"question": "What do you use to cut paper?", "options": ["Spoon", "Fork", "Scissors", "Hammer"], "answer": 2},
    {"question": "Where does the President of the USA live?", "options": ["Pentagon", "White House", "Capitol", "Empire State"], "answer": 1},
    {"question": "How many colors are in a rainbow?", "options": ["5", "6", "7", "8"], "answer": 2}
]